spring.application.name=sayy


spring.datasource.url=jdbc:mysql://localhost:3306/say_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=say
spring.datasource.password=qwe123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8082

# MyBatis
mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.example.sayy.Entity
mybatis.configuration.map-underscore-to-camel-case=true

#
# schema.sql 자동 실행 비활성화 (Flyway로 대체)
spring.sql.init.mode=never

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.encoding=UTF-8
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0


app.admin.username=admin
app.admin.password=test1224

api.service-key=8e71e189d136842a4f7c86012337be3745e11cd310c99c13a595da80f2141b3f

# 업로드(로고 이미지 등) 저장 경로
# - 실행 디렉토리 기준 상대경로 가능 (예: uploads)
app.upload-dir=uploads

# 업로드 용량 제한(로고/직인 등)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


server.tomcat.max-http-form-post-size=50MB

server.tomcat.max-swallow-size=-1